// <auto-generated />
using System;
using HospitalInformationSystem.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalInformationSystem.Shared.Migrations
{
    [DbContext(typeof(HospitalInformationSystemDbContext))]
    [Migration("20210503222509_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HospitalInformationSystem.Shared.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Address2")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ContactRelation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("FileNo")
                        .HasColumnType("decimal(38,0)");

                    b.Property<DateTime?>("FirstVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Natinality")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RecordCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("FileNo")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17a73ff4-1305-4a1c-b1ad-9d143cee3683"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "33356489317",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 32154987431m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(373),
                            Gender = 0,
                            Name = "Ahmet Bakırcı",
                            Natinality = "Syrian",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 690, DateTimeKind.Local).AddTicks(6964),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("40b1f94f-33d7-401d-a2dd-50bf57c755f2"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "55693457810",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "amuhammetbakirci30@gmail.com",
                            FileNo = 9874231674421m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1016),
                            Gender = 0,
                            Name = "Muhammet Bakırcı",
                            Natinality = "Syrian",
                            PhoneNumber = "+905365823893",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1011),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("8326b761-53e1-4099-a8fd-a683b80d9f07"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1997, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "59356489387",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 6516321616058m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1033),
                            Gender = 0,
                            Name = "Ahmet Nehhas",
                            Natinality = "Syrian",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1032),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("e6ea96b2-5f6b-48e4-81f8-79cc46a44e91"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1993, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "98632189317",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 354168102081m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1041),
                            Gender = 1,
                            Name = "Fatma Rıza",
                            Natinality = "Turkish",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1040),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("d51611e2-a357-4547-ad40-50db0ebced50"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "96256489317",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 3234054987431m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1062),
                            Gender = 1,
                            Name = "Halide Bakırcı",
                            Natinality = "Syrian",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1061),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("b038a173-98ab-45db-9b7c-0028a861de21"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1998, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "50699827810",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "amuhammetbakirci30@gmail.com",
                            FileNo = 9874231601491m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1071),
                            Gender = 0,
                            Name = "Nasır Bakırcı",
                            Natinality = "Iraqi",
                            PhoneNumber = "+905365823893",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1070),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("63309baf-321c-4b4c-a30c-2b867b22cb41"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(2003, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "59356409387",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 15163616058m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1079),
                            Gender = 1,
                            Name = "Ritta Safa",
                            Natinality = "Turkish",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1078),
                            Street = "Başak Caddesi"
                        },
                        new
                        {
                            Id = new Guid("e436310f-dce4-4148-a1be-661e1e3fd251"),
                            Address1 = "Fevzi Çakmak Mahallesi 10782. Sokak Uhut Sitesi No:2A/9 Karatay/Konya",
                            Address2 = "Hacıveyiszade Mahallesi Müeyyitzade Sokak No:14/B Karatay/Konya",
                            BirthDate = new DateTime(1991, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CitizenId = "92032189317",
                            City = "Konya",
                            ContactPerson = "Fuat Bakırcı",
                            ContactPhone = "+905366724096",
                            ContactRelation = "Brother",
                            Country = "Turkey",
                            Email = "ahmetbakirci30@gmail.com",
                            FileNo = 3544768102081m,
                            FirstVisitDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1087),
                            Gender = 1,
                            Name = "Fatma Lale",
                            Natinality = "Turk",
                            PhoneNumber = "+905383754105",
                            RecordCreationDate = new DateTime(2021, 5, 4, 1, 25, 8, 691, DateTimeKind.Local).AddTicks(1086),
                            Street = "Başak Caddesi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
